name: CI

on:
  workflow_call:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  backend:
    uses: ./.github/workflows/backend.yml

  web:
    uses: ./.github/workflows/web.yml

  desktop:
    uses: ./.github/workflows/desktop.yml

  docker:
    uses: ./.github/workflows/docker.yml
